//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit.App.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bit.App.Resources.AppResources.fr", typeof(AppResources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        internal static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Bitwarden {
            get {
                return ResourceManager.GetString("Bitwarden", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        internal static string CopyPassword {
            get {
                return ResourceManager.GetString("CopyPassword", resourceCulture);
            }
        }
        
        internal static string CopyUsername {
            get {
                return ResourceManager.GetString("CopyUsername", resourceCulture);
            }
        }
        
        internal static string CozyPass {
            get {
                return ResourceManager.GetString("CozyPass", resourceCulture);
            }
        }
        
        internal static string CozyURL {
            get {
                return ResourceManager.GetString("CozyURL", resourceCulture);
            }
        }
        
        internal static string CozyPassword {
            get {
                return ResourceManager.GetString("CozyPassword", resourceCulture);
            }
        }
        
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        internal static string DoYouReallyWantToDelete {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDelete", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string EditFolder {
            get {
                return ResourceManager.GetString("EditFolder", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        internal static string EmailUs {
            get {
                return ResourceManager.GetString("EmailUs", resourceCulture);
            }
        }
        
        internal static string EmailUsDescription {
            get {
                return ResourceManager.GetString("EmailUsDescription", resourceCulture);
            }
        }
        
        internal static string EnterPIN {
            get {
                return ResourceManager.GetString("EnterPIN", resourceCulture);
            }
        }
        
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        internal static string FileBugReport {
            get {
                return ResourceManager.GetString("FileBugReport", resourceCulture);
            }
        }
        
        internal static string FileBugReportDescription {
            get {
                return ResourceManager.GetString("FileBugReportDescription", resourceCulture);
            }
        }
        
        internal static string FingerprintDirection {
            get {
                return ResourceManager.GetString("FingerprintDirection", resourceCulture);
            }
        }
        
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        internal static string FolderCreated {
            get {
                return ResourceManager.GetString("FolderCreated", resourceCulture);
            }
        }
        
        internal static string FolderDeleted {
            get {
                return ResourceManager.GetString("FolderDeleted", resourceCulture);
            }
        }
        
        internal static string FolderNone {
            get {
                return ResourceManager.GetString("FolderNone", resourceCulture);
            }
        }
        
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        internal static string FolderUpdated {
            get {
                return ResourceManager.GetString("FolderUpdated", resourceCulture);
            }
        }
        
        internal static string GoToWebsite {
            get {
                return ResourceManager.GetString("GoToWebsite", resourceCulture);
            }
        }
        
        internal static string HelpAndFeedback {
            get {
                return ResourceManager.GetString("HelpAndFeedback", resourceCulture);
            }
        }
        
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        internal static string InternetConnectionRequiredMessage {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredMessage", resourceCulture);
            }
        }
        
        internal static string InternetConnectionRequiredTitle {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredTitle", resourceCulture);
            }
        }
        
        internal static string InvalidMasterPassword {
            get {
                return ResourceManager.GetString("InvalidMasterPassword", resourceCulture);
            }
        }
        
        internal static string InvalidPIN {
            get {
                return ResourceManager.GetString("InvalidPIN", resourceCulture);
            }
        }
        
        internal static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        internal static string LogInNoun {
            get {
                return ResourceManager.GetString("LogInNoun", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string LogoutConfirmation {
            get {
                return ResourceManager.GetString("LogoutConfirmation", resourceCulture);
            }
        }
        
        internal static string MasterPassword {
            get {
                return ResourceManager.GetString("MasterPassword", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string MyVault {
            get {
                return ResourceManager.GetString("MyVault", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        internal static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        internal static string URI {
            get {
                return ResourceManager.GetString("URI", resourceCulture);
            }
        }
        
        internal static string UseFingerprintToUnlock {
            get {
                return ResourceManager.GetString("UseFingerprintToUnlock", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string ValidationFieldRequired {
            get {
                return ResourceManager.GetString("ValidationFieldRequired", resourceCulture);
            }
        }
        
        internal static string ValueHasBeenCopied {
            get {
                return ResourceManager.GetString("ValueHasBeenCopied", resourceCulture);
            }
        }
        
        internal static string VerifyFingerprint {
            get {
                return ResourceManager.GetString("VerifyFingerprint", resourceCulture);
            }
        }
        
        internal static string VerifyMasterPassword {
            get {
                return ResourceManager.GetString("VerifyMasterPassword", resourceCulture);
            }
        }
        
        internal static string VerifyPIN {
            get {
                return ResourceManager.GetString("VerifyPIN", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        internal static string VisitOurWebsite {
            get {
                return ResourceManager.GetString("VisitOurWebsite", resourceCulture);
            }
        }
        
        internal static string VisitOurWebsiteDescription {
            get {
                return ResourceManager.GetString("VisitOurWebsiteDescription", resourceCulture);
            }
        }
        
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        internal static string AddAnItem {
            get {
                return ResourceManager.GetString("AddAnItem", resourceCulture);
            }
        }
        
        internal static string AppExtension {
            get {
                return ResourceManager.GetString("AppExtension", resourceCulture);
            }
        }
        
        internal static string AutofillAccessibilityDescription {
            get {
                return ResourceManager.GetString("AutofillAccessibilityDescription", resourceCulture);
            }
        }
        
        internal static string AutofillService {
            get {
                return ResourceManager.GetString("AutofillService", resourceCulture);
            }
        }
        
        internal static string AvoidAmbiguousCharacters {
            get {
                return ResourceManager.GetString("AvoidAmbiguousCharacters", resourceCulture);
            }
        }
        
        internal static string BitwardenAppExtension {
            get {
                return ResourceManager.GetString("BitwardenAppExtension", resourceCulture);
            }
        }
        
        internal static string BitwardenAppExtensionAlert2 {
            get {
                return ResourceManager.GetString("BitwardenAppExtensionAlert2", resourceCulture);
            }
        }
        
        internal static string BitwardenAppExtensionDescription {
            get {
                return ResourceManager.GetString("BitwardenAppExtensionDescription", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillService {
            get {
                return ResourceManager.GetString("BitwardenAutofillService", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillAccessibilityServiceDescription {
            get {
                return ResourceManager.GetString("BitwardenAutofillAccessibilityServiceDescription", resourceCulture);
            }
        }
        
        internal static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        internal static string ChangeEmailConfirmation {
            get {
                return ResourceManager.GetString("ChangeEmailConfirmation", resourceCulture);
            }
        }
        
        internal static string ChangeMasterPassword {
            get {
                return ResourceManager.GetString("ChangeMasterPassword", resourceCulture);
            }
        }
        
        internal static string ChangePasswordConfirmation {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmation", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        internal static string CreatingAccount {
            get {
                return ResourceManager.GetString("CreatingAccount", resourceCulture);
            }
        }
        
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        internal static string EnableAutomaticSyncing {
            get {
                return ResourceManager.GetString("EnableAutomaticSyncing", resourceCulture);
            }
        }
        
        internal static string EnterEmailForHint {
            get {
                return ResourceManager.GetString("EnterEmailForHint", resourceCulture);
            }
        }
        
        internal static string ExntesionReenable {
            get {
                return ResourceManager.GetString("ExntesionReenable", resourceCulture);
            }
        }
        
        internal static string ExtensionAlmostDone {
            get {
                return ResourceManager.GetString("ExtensionAlmostDone", resourceCulture);
            }
        }
        
        internal static string ExtensionEnable {
            get {
                return ResourceManager.GetString("ExtensionEnable", resourceCulture);
            }
        }
        
        internal static string ExtensionInSafari {
            get {
                return ResourceManager.GetString("ExtensionInSafari", resourceCulture);
            }
        }
        
        internal static string ExtensionInstantAccess {
            get {
                return ResourceManager.GetString("ExtensionInstantAccess", resourceCulture);
            }
        }
        
        internal static string ExtensionReady {
            get {
                return ResourceManager.GetString("ExtensionReady", resourceCulture);
            }
        }
        
        internal static string ExtensionSetup {
            get {
                return ResourceManager.GetString("ExtensionSetup", resourceCulture);
            }
        }
        
        internal static string ExtensionSetup2 {
            get {
                return ResourceManager.GetString("ExtensionSetup2", resourceCulture);
            }
        }
        
        internal static string ExtensionTapIcon {
            get {
                return ResourceManager.GetString("ExtensionTapIcon", resourceCulture);
            }
        }
        
        internal static string ExtensionTurnOn {
            get {
                return ResourceManager.GetString("ExtensionTurnOn", resourceCulture);
            }
        }
        
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        internal static string Fingerprint {
            get {
                return ResourceManager.GetString("Fingerprint", resourceCulture);
            }
        }
        
        internal static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }
        
        internal static string GetPasswordHint {
            get {
                return ResourceManager.GetString("GetPasswordHint", resourceCulture);
            }
        }
        
        internal static string ImportItems {
            get {
                return ResourceManager.GetString("ImportItems", resourceCulture);
            }
        }
        
        internal static string ImportItemsConfirmation {
            get {
                return ResourceManager.GetString("ImportItemsConfirmation", resourceCulture);
            }
        }
        
        internal static string ImportItemsDescription {
            get {
                return ResourceManager.GetString("ImportItemsDescription", resourceCulture);
            }
        }
        
        internal static string LastSync {
            get {
                return ResourceManager.GetString("LastSync", resourceCulture);
            }
        }
        
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        internal static string LockOption15Minutes {
            get {
                return ResourceManager.GetString("LockOption15Minutes", resourceCulture);
            }
        }
        
        internal static string LockOption1Hour {
            get {
                return ResourceManager.GetString("LockOption1Hour", resourceCulture);
            }
        }
        
        internal static string LockOption1Minute {
            get {
                return ResourceManager.GetString("LockOption1Minute", resourceCulture);
            }
        }
        
        internal static string LockOption4Hours {
            get {
                return ResourceManager.GetString("LockOption4Hours", resourceCulture);
            }
        }
        
        internal static string LockOptionImmediately {
            get {
                return ResourceManager.GetString("LockOptionImmediately", resourceCulture);
            }
        }
        
        internal static string LockOptions {
            get {
                return ResourceManager.GetString("LockOptions", resourceCulture);
            }
        }
        
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        internal static string LoginOrCreateNewAccount {
            get {
                return ResourceManager.GetString("LoginOrCreateNewAccount", resourceCulture);
            }
        }
        
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        internal static string MasterPasswordConfirmationValMessage {
            get {
                return ResourceManager.GetString("MasterPasswordConfirmationValMessage", resourceCulture);
            }
        }
        
        internal static string MasterPasswordDescription {
            get {
                return ResourceManager.GetString("MasterPasswordDescription", resourceCulture);
            }
        }
        
        internal static string MasterPasswordHint {
            get {
                return ResourceManager.GetString("MasterPasswordHint", resourceCulture);
            }
        }
        
        internal static string MasterPasswordHintDescription {
            get {
                return ResourceManager.GetString("MasterPasswordHintDescription", resourceCulture);
            }
        }
        
        internal static string MasterPasswordLengthValMessage {
            get {
                return ResourceManager.GetString("MasterPasswordLengthValMessage", resourceCulture);
            }
        }
        
        internal static string MinNumbers {
            get {
                return ResourceManager.GetString("MinNumbers", resourceCulture);
            }
        }
        
        internal static string MinSpecial {
            get {
                return ResourceManager.GetString("MinSpecial", resourceCulture);
            }
        }
        
        internal static string MoreSettings {
            get {
                return ResourceManager.GetString("MoreSettings", resourceCulture);
            }
        }
        
        internal static string MustLogInMainApp {
            get {
                return ResourceManager.GetString("MustLogInMainApp", resourceCulture);
            }
        }
        
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        internal static string NewItemCreated {
            get {
                return ResourceManager.GetString("NewItemCreated", resourceCulture);
            }
        }
        
        internal static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        internal static string NoItemsTap {
            get {
                return ResourceManager.GetString("NoItemsTap", resourceCulture);
            }
        }
        
        internal static string NoUsernamePasswordConfigured {
            get {
                return ResourceManager.GetString("NoUsernamePasswordConfigured", resourceCulture);
            }
        }
        
        internal static string OkGotIt {
            get {
                return ResourceManager.GetString("OkGotIt", resourceCulture);
            }
        }
        
        internal static string OptionDefaults {
            get {
                return ResourceManager.GetString("OptionDefaults", resourceCulture);
            }
        }
        
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        internal static string PasswordGenerated {
            get {
                return ResourceManager.GetString("PasswordGenerated", resourceCulture);
            }
        }
        
        internal static string PasswordGenerator {
            get {
                return ResourceManager.GetString("PasswordGenerator", resourceCulture);
            }
        }
        
        internal static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        internal static string PasswordHintAlert {
            get {
                return ResourceManager.GetString("PasswordHintAlert", resourceCulture);
            }
        }
        
        internal static string PasswordOverrideAlert {
            get {
                return ResourceManager.GetString("PasswordOverrideAlert", resourceCulture);
            }
        }
        
        internal static string PushNotificationAlert {
            get {
                return ResourceManager.GetString("PushNotificationAlert", resourceCulture);
            }
        }
        
        internal static string RateTheApp {
            get {
                return ResourceManager.GetString("RateTheApp", resourceCulture);
            }
        }
        
        internal static string RateTheAppDescription {
            get {
                return ResourceManager.GetString("RateTheAppDescription", resourceCulture);
            }
        }
        
        internal static string RegeneratePassword {
            get {
                return ResourceManager.GetString("RegeneratePassword", resourceCulture);
            }
        }
        
        internal static string RetypeMasterPassword {
            get {
                return ResourceManager.GetString("RetypeMasterPassword", resourceCulture);
            }
        }
        
        internal static string SearchVault {
            get {
                return ResourceManager.GetString("SearchVault", resourceCulture);
            }
        }
        
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        internal static string SetPIN {
            get {
                return ResourceManager.GetString("SetPIN", resourceCulture);
            }
        }
        
        internal static string SetPINDirection {
            get {
                return ResourceManager.GetString("SetPINDirection", resourceCulture);
            }
        }
        
        internal static string ItemInformation {
            get {
                return ResourceManager.GetString("ItemInformation", resourceCulture);
            }
        }
        
        internal static string ItemUpdated {
            get {
                return ResourceManager.GetString("ItemUpdated", resourceCulture);
            }
        }
        
        internal static string Submitting {
            get {
                return ResourceManager.GetString("Submitting", resourceCulture);
            }
        }
        
        internal static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        internal static string SyncingComplete {
            get {
                return ResourceManager.GetString("SyncingComplete", resourceCulture);
            }
        }
        
        internal static string SyncingFailed {
            get {
                return ResourceManager.GetString("SyncingFailed", resourceCulture);
            }
        }
        
        internal static string SyncVaultNow {
            get {
                return ResourceManager.GetString("SyncVaultNow", resourceCulture);
            }
        }
        
        internal static string TouchID {
            get {
                return ResourceManager.GetString("TouchID", resourceCulture);
            }
        }
        
        internal static string TwoStepLogin {
            get {
                return ResourceManager.GetString("TwoStepLogin", resourceCulture);
            }
        }
        
        internal static string TwoStepLoginConfirmation {
            get {
                return ResourceManager.GetString("TwoStepLoginConfirmation", resourceCulture);
            }
        }
        
        internal static string UnlockWith {
            get {
                return ResourceManager.GetString("UnlockWith", resourceCulture);
            }
        }
        
        internal static string UnlockWithPIN {
            get {
                return ResourceManager.GetString("UnlockWithPIN", resourceCulture);
            }
        }
        
        internal static string Validating {
            get {
                return ResourceManager.GetString("Validating", resourceCulture);
            }
        }
        
        internal static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        internal static string ViewItem {
            get {
                return ResourceManager.GetString("ViewItem", resourceCulture);
            }
        }
        
        internal static string WebVault {
            get {
                return ResourceManager.GetString("WebVault", resourceCulture);
            }
        }
        
        internal static string Lost2FAApp {
            get {
                return ResourceManager.GetString("Lost2FAApp", resourceCulture);
            }
        }
        
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        internal static string ExtensionActivated {
            get {
                return ResourceManager.GetString("ExtensionActivated", resourceCulture);
            }
        }
        
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        internal static string ItemsForUri {
            get {
                return ResourceManager.GetString("ItemsForUri", resourceCulture);
            }
        }
        
        internal static string NoItemsForUri {
            get {
                return ResourceManager.GetString("NoItemsForUri", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceNotification {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceNotification", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceNotificationContent {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceNotificationContent", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceOpenAccessibilitySettings {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceOpenAccessibilitySettings", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceStep1 {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceStep1", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceStep2 {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceStep2", resourceCulture);
            }
        }
        
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceAlert2 {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceAlert2", resourceCulture);
            }
        }
        
        internal static string Autofill {
            get {
                return ResourceManager.GetString("Autofill", resourceCulture);
            }
        }
        
        internal static string AutofillOrView {
            get {
                return ResourceManager.GetString("AutofillOrView", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceMatchConfirm {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceMatchConfirm", resourceCulture);
            }
        }
        
        internal static string MatchingItems {
            get {
                return ResourceManager.GetString("MatchingItems", resourceCulture);
            }
        }
        
        internal static string PossibleMatchingItems {
            get {
                return ResourceManager.GetString("PossibleMatchingItems", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceSearch {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceSearch", resourceCulture);
            }
        }
        
        internal static string ShareVault {
            get {
                return ResourceManager.GetString("ShareVault", resourceCulture);
            }
        }
        
        internal static string AutofillPasswordField {
            get {
                return ResourceManager.GetString("AutofillPasswordField", resourceCulture);
            }
        }
        
        internal static string AutofillPasswordFieldDescription {
            get {
                return ResourceManager.GetString("AutofillPasswordFieldDescription", resourceCulture);
            }
        }
        
        internal static string AutofillPersistNotification {
            get {
                return ResourceManager.GetString("AutofillPersistNotification", resourceCulture);
            }
        }
        
        internal static string AutofillPersistNotificationDescription {
            get {
                return ResourceManager.GetString("AutofillPersistNotificationDescription", resourceCulture);
            }
        }
        
        internal static string AutofillAlways {
            get {
                return ResourceManager.GetString("AutofillAlways", resourceCulture);
            }
        }
        
        internal static string AutofillAlwaysDescription {
            get {
                return ResourceManager.GetString("AutofillAlwaysDescription", resourceCulture);
            }
        }
        
        internal static string CannotOpenApp {
            get {
                return ResourceManager.GetString("CannotOpenApp", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAppTitle {
            get {
                return ResourceManager.GetString("AuthenticatorAppTitle", resourceCulture);
            }
        }
        
        internal static string EnterVerificationCodeApp {
            get {
                return ResourceManager.GetString("EnterVerificationCodeApp", resourceCulture);
            }
        }
        
        internal static string EnterVerificationCodeEmail {
            get {
                return ResourceManager.GetString("EnterVerificationCodeEmail", resourceCulture);
            }
        }
        
        internal static string LoginUnavailable {
            get {
                return ResourceManager.GetString("LoginUnavailable", resourceCulture);
            }
        }
        
        internal static string NoTwoStepAvailable {
            get {
                return ResourceManager.GetString("NoTwoStepAvailable", resourceCulture);
            }
        }
        
        internal static string RecoveryCodeTitle {
            get {
                return ResourceManager.GetString("RecoveryCodeTitle", resourceCulture);
            }
        }
        
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        internal static string SendVerificationCodeAgain {
            get {
                return ResourceManager.GetString("SendVerificationCodeAgain", resourceCulture);
            }
        }
        
        internal static string TwoStepLoginOptions {
            get {
                return ResourceManager.GetString("TwoStepLoginOptions", resourceCulture);
            }
        }
        
        internal static string UseAnotherTwoStepMethod {
            get {
                return ResourceManager.GetString("UseAnotherTwoStepMethod", resourceCulture);
            }
        }
        
        internal static string VerificationEmailNotSent {
            get {
                return ResourceManager.GetString("VerificationEmailNotSent", resourceCulture);
            }
        }
        
        internal static string VerificationEmailSent {
            get {
                return ResourceManager.GetString("VerificationEmailSent", resourceCulture);
            }
        }
        
        internal static string YubiKeyInstruction {
            get {
                return ResourceManager.GetString("YubiKeyInstruction", resourceCulture);
            }
        }
        
        internal static string YubiKeyTitle {
            get {
                return ResourceManager.GetString("YubiKeyTitle", resourceCulture);
            }
        }
        
        internal static string AddNewAttachment {
            get {
                return ResourceManager.GetString("AddNewAttachment", resourceCulture);
            }
        }
        
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        internal static string UnableToDownloadFile {
            get {
                return ResourceManager.GetString("UnableToDownloadFile", resourceCulture);
            }
        }
        
        internal static string UnableToOpenFile {
            get {
                return ResourceManager.GetString("UnableToOpenFile", resourceCulture);
            }
        }
        
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        internal static string AttachmentLargeWarning {
            get {
                return ResourceManager.GetString("AttachmentLargeWarning", resourceCulture);
            }
        }
        
        internal static string AuthenticatorKey {
            get {
                return ResourceManager.GetString("AuthenticatorKey", resourceCulture);
            }
        }
        
        internal static string VerificationCodeTotp {
            get {
                return ResourceManager.GetString("VerificationCodeTotp", resourceCulture);
            }
        }
        
        internal static string AuthenticatorKeyAdded {
            get {
                return ResourceManager.GetString("AuthenticatorKeyAdded", resourceCulture);
            }
        }
        
        internal static string AuthenticatorKeyReadError {
            get {
                return ResourceManager.GetString("AuthenticatorKeyReadError", resourceCulture);
            }
        }
        
        internal static string CameraInstructionBottom {
            get {
                return ResourceManager.GetString("CameraInstructionBottom", resourceCulture);
            }
        }
        
        internal static string CameraInstructionTop {
            get {
                return ResourceManager.GetString("CameraInstructionTop", resourceCulture);
            }
        }
        
        internal static string ScanQrTitle {
            get {
                return ResourceManager.GetString("ScanQrTitle", resourceCulture);
            }
        }
        
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        internal static string CopyTotp {
            get {
                return ResourceManager.GetString("CopyTotp", resourceCulture);
            }
        }
        
        internal static string DisableAutoTotpCopyDescription {
            get {
                return ResourceManager.GetString("DisableAutoTotpCopyDescription", resourceCulture);
            }
        }
        
        internal static string DisableAutoTotpCopy {
            get {
                return ResourceManager.GetString("DisableAutoTotpCopy", resourceCulture);
            }
        }
        
        internal static string PremiumRequired {
            get {
                return ResourceManager.GetString("PremiumRequired", resourceCulture);
            }
        }
        
        internal static string AttachementAdded {
            get {
                return ResourceManager.GetString("AttachementAdded", resourceCulture);
            }
        }
        
        internal static string AttachmentDeleted {
            get {
                return ResourceManager.GetString("AttachmentDeleted", resourceCulture);
            }
        }
        
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        internal static string NoFileChosen {
            get {
                return ResourceManager.GetString("NoFileChosen", resourceCulture);
            }
        }
        
        internal static string NoAttachments {
            get {
                return ResourceManager.GetString("NoAttachments", resourceCulture);
            }
        }
        
        internal static string FileSource {
            get {
                return ResourceManager.GetString("FileSource", resourceCulture);
            }
        }
        
        internal static string FeatureUnavailable {
            get {
                return ResourceManager.GetString("FeatureUnavailable", resourceCulture);
            }
        }
        
        internal static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        internal static string UpdateKey {
            get {
                return ResourceManager.GetString("UpdateKey", resourceCulture);
            }
        }
        
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        internal static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        internal static string CustomEnvironment {
            get {
                return ResourceManager.GetString("CustomEnvironment", resourceCulture);
            }
        }
        
        internal static string CustomEnvironmentFooter {
            get {
                return ResourceManager.GetString("CustomEnvironmentFooter", resourceCulture);
            }
        }
        
        internal static string EnvironmentSaved {
            get {
                return ResourceManager.GetString("EnvironmentSaved", resourceCulture);
            }
        }
        
        internal static string FormattedIncorrectly {
            get {
                return ResourceManager.GetString("FormattedIncorrectly", resourceCulture);
            }
        }
        
        internal static string IdentityUrl {
            get {
                return ResourceManager.GetString("IdentityUrl", resourceCulture);
            }
        }
        
        internal static string SelfHostedEnvironment {
            get {
                return ResourceManager.GetString("SelfHostedEnvironment", resourceCulture);
            }
        }
        
        internal static string SelfHostedEnvironmentFooter {
            get {
                return ResourceManager.GetString("SelfHostedEnvironmentFooter", resourceCulture);
            }
        }
        
        internal static string ServerUrl {
            get {
                return ResourceManager.GetString("ServerUrl", resourceCulture);
            }
        }
        
        internal static string WebVaultUrl {
            get {
                return ResourceManager.GetString("WebVaultUrl", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceNotificationContentOld {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceNotificationContentOld", resourceCulture);
            }
        }
        
        internal static string CustomFields {
            get {
                return ResourceManager.GetString("CustomFields", resourceCulture);
            }
        }
        
        internal static string CopyNumber {
            get {
                return ResourceManager.GetString("CopyNumber", resourceCulture);
            }
        }
        
        internal static string CopySecurityCode {
            get {
                return ResourceManager.GetString("CopySecurityCode", resourceCulture);
            }
        }
        
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        internal static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        internal static string TypeCard {
            get {
                return ResourceManager.GetString("TypeCard", resourceCulture);
            }
        }
        
        internal static string TypeIdentity {
            get {
                return ResourceManager.GetString("TypeIdentity", resourceCulture);
            }
        }
        
        internal static string TypeLogin {
            get {
                return ResourceManager.GetString("TypeLogin", resourceCulture);
            }
        }
        
        internal static string TypeSecureNote {
            get {
                return ResourceManager.GetString("TypeSecureNote", resourceCulture);
            }
        }
        
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        internal static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        internal static string CardholderName {
            get {
                return ResourceManager.GetString("CardholderName", resourceCulture);
            }
        }
        
        internal static string CityTown {
            get {
                return ResourceManager.GetString("CityTown", resourceCulture);
            }
        }
        
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        internal static string Dr {
            get {
                return ResourceManager.GetString("Dr", resourceCulture);
            }
        }
        
        internal static string ExpirationMonth {
            get {
                return ResourceManager.GetString("ExpirationMonth", resourceCulture);
            }
        }
        
        internal static string ExpirationYear {
            get {
                return ResourceManager.GetString("ExpirationYear", resourceCulture);
            }
        }
        
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        internal static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        internal static string Mrs {
            get {
                return ResourceManager.GetString("Mrs", resourceCulture);
            }
        }
        
        internal static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        internal static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        internal static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        internal static string StateProvince {
            get {
                return ResourceManager.GetString("StateProvince", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string ZipPostalCode {
            get {
                return ResourceManager.GetString("ZipPostalCode", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        internal static string DisableWebsiteIcons {
            get {
                return ResourceManager.GetString("DisableWebsiteIcons", resourceCulture);
            }
        }
        
        internal static string DisableWebsiteIconsDescription {
            get {
                return ResourceManager.GetString("DisableWebsiteIconsDescription", resourceCulture);
            }
        }
        
        internal static string IconsUrl {
            get {
                return ResourceManager.GetString("IconsUrl", resourceCulture);
            }
        }
        
        internal static string AutofillWithBitwarden {
            get {
                return ResourceManager.GetString("AutofillWithBitwarden", resourceCulture);
            }
        }
        
        internal static string VaultIsLocked {
            get {
                return ResourceManager.GetString("VaultIsLocked", resourceCulture);
            }
        }
        
        internal static string GoToMyVault {
            get {
                return ResourceManager.GetString("GoToMyVault", resourceCulture);
            }
        }
        
        internal static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        internal static string NoItemsCollection {
            get {
                return ResourceManager.GetString("NoItemsCollection", resourceCulture);
            }
        }
        
        internal static string NoItemsFolder {
            get {
                return ResourceManager.GetString("NoItemsFolder", resourceCulture);
            }
        }
        
        internal static string AutofillAccessibilityService {
            get {
                return ResourceManager.GetString("AutofillAccessibilityService", resourceCulture);
            }
        }
        
        internal static string AutofillServiceDescription {
            get {
                return ResourceManager.GetString("AutofillServiceDescription", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceDescription {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceDescription", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillServiceOpenAutofillSettings {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceOpenAutofillSettings", resourceCulture);
            }
        }
        
        internal static string FaceID {
            get {
                return ResourceManager.GetString("FaceID", resourceCulture);
            }
        }
        
        internal static string FaceIDDirection {
            get {
                return ResourceManager.GetString("FaceIDDirection", resourceCulture);
            }
        }
        
        internal static string UseFaceIDToUnlock {
            get {
                return ResourceManager.GetString("UseFaceIDToUnlock", resourceCulture);
            }
        }
        
        internal static string VerifyFaceID {
            get {
                return ResourceManager.GetString("VerifyFaceID", resourceCulture);
            }
        }
        
        internal static string WindowsHello {
            get {
                return ResourceManager.GetString("WindowsHello", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillGoToSettings {
            get {
                return ResourceManager.GetString("BitwardenAutofillGoToSettings", resourceCulture);
            }
        }
        
        internal static string CustomFieldName {
            get {
                return ResourceManager.GetString("CustomFieldName", resourceCulture);
            }
        }
        
        internal static string FieldTypeBoolean {
            get {
                return ResourceManager.GetString("FieldTypeBoolean", resourceCulture);
            }
        }
        
        internal static string FieldTypeHidden {
            get {
                return ResourceManager.GetString("FieldTypeHidden", resourceCulture);
            }
        }
        
        internal static string FieldTypeText {
            get {
                return ResourceManager.GetString("FieldTypeText", resourceCulture);
            }
        }
        
        internal static string NewCustomField {
            get {
                return ResourceManager.GetString("NewCustomField", resourceCulture);
            }
        }
        
        internal static string SelectTypeField {
            get {
                return ResourceManager.GetString("SelectTypeField", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string NewUri {
            get {
                return ResourceManager.GetString("NewUri", resourceCulture);
            }
        }
        
        internal static string URIPosition {
            get {
                return ResourceManager.GetString("URIPosition", resourceCulture);
            }
        }
        
        internal static string BaseDomain {
            get {
                return ResourceManager.GetString("BaseDomain", resourceCulture);
            }
        }
        
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        internal static string Exact {
            get {
                return ResourceManager.GetString("Exact", resourceCulture);
            }
        }
        
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        internal static string RegEx {
            get {
                return ResourceManager.GetString("RegEx", resourceCulture);
            }
        }
        
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        internal static string URIMatchDetection {
            get {
                return ResourceManager.GetString("URIMatchDetection", resourceCulture);
            }
        }
        
        internal static string MatchDetection {
            get {
                return ResourceManager.GetString("MatchDetection", resourceCulture);
            }
        }
        
        internal static string YesAndSave {
            get {
                return ResourceManager.GetString("YesAndSave", resourceCulture);
            }
        }
        
        internal static string AutofillAndSave {
            get {
                return ResourceManager.GetString("AutofillAndSave", resourceCulture);
            }
        }
        
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        internal static string HoldYubikeyNearTop {
            get {
                return ResourceManager.GetString("HoldYubikeyNearTop", resourceCulture);
            }
        }
        
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        internal static string YubiKeyInstructionIos {
            get {
                return ResourceManager.GetString("YubiKeyInstructionIos", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillAccessibilityServiceDescription2 {
            get {
                return ResourceManager.GetString("BitwardenAutofillAccessibilityServiceDescription2", resourceCulture);
            }
        }
        
        internal static string DatePasswordUpdated {
            get {
                return ResourceManager.GetString("DatePasswordUpdated", resourceCulture);
            }
        }
        
        internal static string DateUpdated {
            get {
                return ResourceManager.GetString("DateUpdated", resourceCulture);
            }
        }
        
        internal static string AutofillActivated {
            get {
                return ResourceManager.GetString("AutofillActivated", resourceCulture);
            }
        }
        
        internal static string MustLogInMainAppAutofill {
            get {
                return ResourceManager.GetString("MustLogInMainAppAutofill", resourceCulture);
            }
        }
        
        internal static string AutofillSetup {
            get {
                return ResourceManager.GetString("AutofillSetup", resourceCulture);
            }
        }
        
        internal static string AutofillSetup2 {
            get {
                return ResourceManager.GetString("AutofillSetup2", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillDescription {
            get {
                return ResourceManager.GetString("BitwardenAutofillDescription", resourceCulture);
            }
        }
        
        internal static string AutofillTurnOn {
            get {
                return ResourceManager.GetString("AutofillTurnOn", resourceCulture);
            }
        }
        
        internal static string AutofillTurnOn1 {
            get {
                return ResourceManager.GetString("AutofillTurnOn1", resourceCulture);
            }
        }
        
        internal static string AutofillTurnOn2 {
            get {
                return ResourceManager.GetString("AutofillTurnOn2", resourceCulture);
            }
        }
        
        internal static string AutofillTurnOn3 {
            get {
                return ResourceManager.GetString("AutofillTurnOn3", resourceCulture);
            }
        }
        
        internal static string AutofillTurnOn4 {
            get {
                return ResourceManager.GetString("AutofillTurnOn4", resourceCulture);
            }
        }
        
        internal static string AutofillTurnOn5 {
            get {
                return ResourceManager.GetString("AutofillTurnOn5", resourceCulture);
            }
        }
        
        internal static string PasswordAutofill {
            get {
                return ResourceManager.GetString("PasswordAutofill", resourceCulture);
            }
        }
        
        internal static string BitwardenAutofillAlert2 {
            get {
                return ResourceManager.GetString("BitwardenAutofillAlert2", resourceCulture);
            }
        }
        
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        internal static string Identities {
            get {
                return ResourceManager.GetString("Identities", resourceCulture);
            }
        }
        
        internal static string Logins {
            get {
                return ResourceManager.GetString("Logins", resourceCulture);
            }
        }
        
        internal static string SecureNotes {
            get {
                return ResourceManager.GetString("SecureNotes", resourceCulture);
            }
        }
        
        internal static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        internal static string URIs {
            get {
                return ResourceManager.GetString("URIs", resourceCulture);
            }
        }
        
        internal static string CheckingPassword {
            get {
                return ResourceManager.GetString("CheckingPassword", resourceCulture);
            }
        }
        
        internal static string CheckPassword {
            get {
                return ResourceManager.GetString("CheckPassword", resourceCulture);
            }
        }
        
        internal static string PasswordExposed {
            get {
                return ResourceManager.GetString("PasswordExposed", resourceCulture);
            }
        }
        
        internal static string PasswordSafe {
            get {
                return ResourceManager.GetString("PasswordSafe", resourceCulture);
            }
        }
        
        internal static string IdentityName {
            get {
                return ResourceManager.GetString("IdentityName", resourceCulture);
            }
        }
        
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static string PasswordHistory {
            get {
                return ResourceManager.GetString("PasswordHistory", resourceCulture);
            }
        }
        
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        internal static string NoPasswordsToList {
            get {
                return ResourceManager.GetString("NoPasswordsToList", resourceCulture);
            }
        }
        
        internal static string NoItemsToList {
            get {
                return ResourceManager.GetString("NoItemsToList", resourceCulture);
            }
        }
        
        internal static string SearchCollection {
            get {
                return ResourceManager.GetString("SearchCollection", resourceCulture);
            }
        }
        
        internal static string SearchFolder {
            get {
                return ResourceManager.GetString("SearchFolder", resourceCulture);
            }
        }
        
        internal static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        internal static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        internal static string Ownership {
            get {
                return ResourceManager.GetString("Ownership", resourceCulture);
            }
        }
        
        internal static string WhoOwnsThisItem {
            get {
                return ResourceManager.GetString("WhoOwnsThisItem", resourceCulture);
            }
        }
        
        internal static string NoCollectionsToList {
            get {
                return ResourceManager.GetString("NoCollectionsToList", resourceCulture);
            }
        }
        
        internal static string ItemShared {
            get {
                return ResourceManager.GetString("ItemShared", resourceCulture);
            }
        }
        
        internal static string SelectOneCollection {
            get {
                return ResourceManager.GetString("SelectOneCollection", resourceCulture);
            }
        }
        
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        internal static string ShareItem {
            get {
                return ResourceManager.GetString("ShareItem", resourceCulture);
            }
        }
        
        internal static string NoOrgsToList {
            get {
                return ResourceManager.GetString("NoOrgsToList", resourceCulture);
            }
        }
        
        internal static string ShareDesc {
            get {
                return ResourceManager.GetString("ShareDesc", resourceCulture);
            }
        }
        
        internal static string NumberOfWords {
            get {
                return ResourceManager.GetString("NumberOfWords", resourceCulture);
            }
        }
        
        internal static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        internal static string WordSeparator {
            get {
                return ResourceManager.GetString("WordSeparator", resourceCulture);
            }
        }
        
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        internal static string NoFoldersToList {
            get {
                return ResourceManager.GetString("NoFoldersToList", resourceCulture);
            }
        }
        
        internal static string FingerprintPhrase {
            get {
                return ResourceManager.GetString("FingerprintPhrase", resourceCulture);
            }
        }
        
        internal static string YourAccountsFingerprint {
            get {
                return ResourceManager.GetString("YourAccountsFingerprint", resourceCulture);
            }
        }
        
        internal static string ShareVaultConfirmation {
            get {
                return ResourceManager.GetString("ShareVaultConfirmation", resourceCulture);
            }
        }
        
        internal static string ExportVault {
            get {
                return ResourceManager.GetString("ExportVault", resourceCulture);
            }
        }
        
        internal static string LockNow {
            get {
                return ResourceManager.GetString("LockNow", resourceCulture);
            }
        }
        
        internal static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        internal static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        internal static string LockOption30Minutes {
            get {
                return ResourceManager.GetString("LockOption30Minutes", resourceCulture);
            }
        }
        
        internal static string LockOption5Minutes {
            get {
                return ResourceManager.GetString("LockOption5Minutes", resourceCulture);
            }
        }
        
        internal static string SetPINDescription {
            get {
                return ResourceManager.GetString("SetPINDescription", resourceCulture);
            }
        }
        
        internal static string LoggedInAsOn {
            get {
                return ResourceManager.GetString("LoggedInAsOn", resourceCulture);
            }
        }
        
        internal static string VaultLockedMasterPassword {
            get {
                return ResourceManager.GetString("VaultLockedMasterPassword", resourceCulture);
            }
        }
        
        internal static string VaultLockedPIN {
            get {
                return ResourceManager.GetString("VaultLockedPIN", resourceCulture);
            }
        }
        
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        internal static string FiveMinutes {
            get {
                return ResourceManager.GetString("FiveMinutes", resourceCulture);
            }
        }
        
        internal static string OneMinute {
            get {
                return ResourceManager.GetString("OneMinute", resourceCulture);
            }
        }
        
        internal static string TenSeconds {
            get {
                return ResourceManager.GetString("TenSeconds", resourceCulture);
            }
        }
        
        internal static string ThirtySeconds {
            get {
                return ResourceManager.GetString("ThirtySeconds", resourceCulture);
            }
        }
        
        internal static string TwentySeconds {
            get {
                return ResourceManager.GetString("TwentySeconds", resourceCulture);
            }
        }
        
        internal static string TwoMinutes {
            get {
                return ResourceManager.GetString("TwoMinutes", resourceCulture);
            }
        }
        
        internal static string ClearClipboard {
            get {
                return ResourceManager.GetString("ClearClipboard", resourceCulture);
            }
        }
        
        internal static string ClearClipboardDescription {
            get {
                return ResourceManager.GetString("ClearClipboardDescription", resourceCulture);
            }
        }
        
        internal static string DefaultUriMatchDetection {
            get {
                return ResourceManager.GetString("DefaultUriMatchDetection", resourceCulture);
            }
        }
        
        internal static string DefaultUriMatchDetectionDescription {
            get {
                return ResourceManager.GetString("DefaultUriMatchDetectionDescription", resourceCulture);
            }
        }
        
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        internal static string ThemeDescription {
            get {
                return ResourceManager.GetString("ThemeDescription", resourceCulture);
            }
        }
        
        internal static string RestartIsRequired {
            get {
                return ResourceManager.GetString("RestartIsRequired", resourceCulture);
            }
        }
        
        internal static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        internal static string CopyNotes {
            get {
                return ResourceManager.GetString("CopyNotes", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        internal static string PINRequireMasterPasswordRestart {
            get {
                return ResourceManager.GetString("PINRequireMasterPasswordRestart", resourceCulture);
            }
        }
        
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        internal static string BlacklistedUris {
            get {
                return ResourceManager.GetString("BlacklistedUris", resourceCulture);
            }
        }
        
        internal static string BlacklistedUrisDescription {
            get {
                return ResourceManager.GetString("BlacklistedUrisDescription", resourceCulture);
            }
        }
        
        internal static string DisableSavePrompt {
            get {
                return ResourceManager.GetString("DisableSavePrompt", resourceCulture);
            }
        }
        
        internal static string DisableSavePromptDescription {
            get {
                return ResourceManager.GetString("DisableSavePromptDescription", resourceCulture);
            }
        }
        
        internal static string LockOptionOnRestart {
            get {
                return ResourceManager.GetString("LockOptionOnRestart", resourceCulture);
            }
        }
        
        internal static string AutofillServiceNotEnabled {
            get {
                return ResourceManager.GetString("AutofillServiceNotEnabled", resourceCulture);
            }
        }
        
        internal static string ThemeAppliedOnRestart {
            get {
                return ResourceManager.GetString("ThemeAppliedOnRestart", resourceCulture);
            }
        }
        
        internal static string Capitalize {
            get {
                return ResourceManager.GetString("Capitalize", resourceCulture);
            }
        }
        
        internal static string IncludeNumber {
            get {
                return ResourceManager.GetString("IncludeNumber", resourceCulture);
            }
        }
        
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        internal static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        internal static string ToggleVisibility {
            get {
                return ResourceManager.GetString("ToggleVisibility", resourceCulture);
            }
        }
        
        internal static string LoginExpired {
            get {
                return ResourceManager.GetString("LoginExpired", resourceCulture);
            }
        }
        
        internal static string BiometricsDirection {
            get {
                return ResourceManager.GetString("BiometricsDirection", resourceCulture);
            }
        }
        
        internal static string Biometrics {
            get {
                return ResourceManager.GetString("Biometrics", resourceCulture);
            }
        }
        
        internal static string UseBiometricsToUnlock {
            get {
                return ResourceManager.GetString("UseBiometricsToUnlock", resourceCulture);
            }
        }
    }
}
